### PR TITLE
dynamic delay: fix pending bytes rate calculation

### LINKED ISSUE #431: dynamic delay: fix calculation when range is small
fix CalculateWriteDelayDividerAndMaybeUpdateWriteStallCause when calculating pending compaction bytes. 
use number of steps instead of fixed size steps of 1G.

### PR DESCRIPTION
**Pull request by Yuval-Ariel**
closes #431 
use fixed num delay steps instead of fixing the step size and deducing the num steps.
this makes the code simpler and avoids a bug when the excess bytes are greater than num_steps * step_size which then fails the assert: assert(step_num < num_steps);  - since step_num == num_steps.

### CODE REVIEW

File: db/column_family.cc [hunk 1]
```diff
@@ -1001,21 +1002,19 @@ ColumnFamilyData::CalculateWriteDelayDividerAndMaybeUpdateWriteStallCause(
...
-    uint64_t num_steps = soft_hard_range / step_size;
-    auto extra_bytes = compaction_needed_bytes - soft_limit;
-    auto step_num = static_cast<uint64_t>(extra_bytes / step_size);
-    assert(step_num < num_steps);
-    if (num_steps > 0) {
-      pending_divider = 1 / (1 - (static_cast<double>(step_num) / num_steps));
-    }
+    uint64_t step_size = ceil(soft_hard_range / kNumPendingSteps);
+    uint64_t extra_bytes = compaction_needed_bytes - soft_limit;
+    assert(extra_bytes > 0);
```
Comment (RoyBenMoshe) [inline db/column_family.cc:1013]: I think this condition is always true

**Review by RoyBenMoshe — APPROVED** [review]

File: db/column_family.cc (hunk 1 above)
Comment (Yuval-Ariel) [reply db/column_family.cc:1013]: you're right, useless assert indeed. i'll remove it

Comment (Yuval-Ariel) [reply db/column_family.cc]: removed. plz reapprove @RoyBenMoshe

**Review by RoyBenMoshe — DISMISSED** [review]

**Comment by Yuval-Ariel** [comment]
@RoyBenMoshe  one last time (hopefully)

**Review by RoyBenMoshe — APPROVED** [review]

**Comment by Yuval-Ariel** [comment]
passed performance tests - large obj and small db with single disk both. no degradation
https://admin.speedb.io/performance?items=RBXHrqju2327X8XshdBu&items=C9qIa3go368igM6YoR3L&colors=%23F06292&colors=%232e7d32 
https://admin.speedb.io/performance?items=WnH1m2z4tUwLVJ9a4KJY&items=2SDJCDUFoZO60PyAfoCM&colors=%23F06292&colors=%232e7d32
